# Data Transformation and Normalization

# Shanghai PM2.5 Data
## Source: Kaggle

In [1]:
import pandas as pd
import numpy as np

In [8]:
shanghai = pd.read_csv("D:\DATA MINING\shanghai.csv")
shanghai.tail()

No  year  month  day  hour  PM_Jingan  DEWP   HUMI    PRES  TEMP  \
52579  52580  2015     12   31    19       86.0  -1.0  65.13  1035.0   5.0   
52580  52581  2015     12   31    20       83.0   1.0  70.27  1035.0   6.0   
52581  52582  2015     12   31    21       85.0   1.0  70.27  1036.0   6.0   
52582  52583  2015     12   31    22       83.0   0.0  70.06  1035.0   5.0   
52583  52584  2015     12   31    23        NaN   0.0  70.06  1035.0   5.0   

        Iws  precipitation  Iprec  
52579  15.0            0.0    0.0  
52580  19.0            0.0    0.0  
52581  22.0            0.0    0.0  
52582  25.0            0.0    0.0  
52583  27.0            0.0    0.0

# 1. Missing Value

In [9]:
#Identifikasi Missing Value
np.sum(shanghai.isnull())

No                   0
year                 0
month                0
day                  0
hour                 0
PM_Jingan        27884
DEWP                13
HUMI                13
PRES                28
TEMP                13
Iws                 12
precipitation     4009
Iprec             4009
dtype: int64

In [10]:
shanghai.describe()

No          year         month           day          hour  \
count  52584.000000  52584.000000  52584.000000  52584.000000  52584.000000   
mean   26292.500000   2012.499772      6.523962     15.726609     11.500000   
std    15179.837614      1.707485      3.448452      8.798896      6.922252   
min        1.000000   2010.000000      1.000000      1.000000      0.000000   
25%    13146.750000   2011.000000      4.000000      8.000000      5.750000   
50%    26292.500000   2012.000000      7.000000     16.000000     11.500000   
75%    39438.250000   2014.000000     10.000000     23.000000     17.250000   
max    52584.000000   2015.000000     12.000000     31.000000     23.000000   

          PM_Jingan          DEWP          HUMI          PRES          TEMP  \
count  24700.000000  52571.000000  52571.000000  52556.000000  52571.000000   
mean      57.395992     11.295372     69.545646   1016.017564     17.471115   
std       47.616179      9.877649     17.658942      9.016829      9.315528   
min        1.000000    -21.000000     11.320000    990.000000     -5.000000   
25%       26.000000      3.000000     57.930000   1008.100000     10.000000   
50%       44.000000     12.000000     72.420000   1016.000000     18.000000   
75%       73.000000     20.000000     83.370000   1023.000000     25.000000   
max      635.000000     28.000000    100.000000   1040.000000     41.000000   

                Iws  precipitation         Iprec  
count  52572.000000   48575.000000  48575.000000  
mean      49.602367       0.142001      0.935362  
std       78.283572       1.065094      6.586855  
min        0.000000       0.000000      0.000000  
25%        6.000000       0.000000      0.000000  
50%       20.000000       0.000000      0.000000  
75%       61.000000       0.000000      0.000000  
max     1110.000000      61.600000    226.400000

In [11]:
#Filling Missing Value

shanghai['PM_Jingan']=shanghai['PM_Jingan'].fillna(shanghai['PM_Jingan'].mean())
shanghai['DEWP']=shanghai['DEWP'].fillna(shanghai['DEWP'].mean())
shanghai['HUMI']=shanghai['HUMI'].fillna(shanghai['HUMI'].mean())
shanghai['PRES']=shanghai['PRES'].fillna(shanghai['PRES'].mean())
shanghai['TEMP']=shanghai['TEMP'].fillna(shanghai['TEMP'].mean())
shanghai['Iws']=shanghai['Iws'].fillna(shanghai['Iws'].mean())
shanghai['precipitation']=shanghai['precipitation'].fillna(shanghai['precipitation'].mean())
shanghai['Iprec']=shanghai['Iprec'].fillna(shanghai['Iprec'].mean())

np.sum(shanghai.isnull())

No               0
year             0
month            0
day              0
hour             0
PM_Jingan        0
DEWP             0
HUMI             0
PRES             0
TEMP             0
Iws              0
precipitation    0
Iprec            0
dtype: int64

In [17]:
from sklearn.feature_selection import f_regression
x=shanghai.iloc[:,6:11]
y = shanghai.iloc[:,5]

In [18]:
x.tail()

DEWP   HUMI    PRES  TEMP   Iws
52579  -1.0  65.13  1035.0   5.0  15.0
52580   1.0  70.27  1035.0   6.0  19.0
52581   1.0  70.27  1036.0   6.0  22.0
52582   0.0  70.06  1035.0   5.0  25.0
52583   0.0  70.06  1035.0   5.0  27.0

In [19]:
y.tail()

52579    86.000000
52580    83.000000
52581    85.000000
52582    83.000000
52583    57.395992
Name: PM_Jingan, dtype: float64

In [21]:
import statsmodels.formula.api as stat
model1 = stat.ols("y ~ x" , data=shanghai).fit()
print(model1.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.040
Model:                            OLS   Adj. R-squared:                  0.040
Method:                 Least Squares   F-statistic:                     439.1
Date:                Sun, 10 Mar 2019   Prob (F-statistic):               0.00
Time:                        20:32:50   Log-Likelihood:            -2.5681e+05
No. Observations:               52584   AIC:                         5.136e+05
Df Residuals:                   52578   BIC:                         5.137e+05
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    464.0122     34.090     13.611      0.0

# 2. Missing Value, Outlier

In [22]:
from scipy.stats import stats
z= np.abs(stats.zscore(shanghai._get_numeric_data()))
print(z)
shanghai2=shanghai[(z<3).all(axis=1)]
print(shanghai2.shape)

[[1.73201787 1.46402199 1.60188207 ... 0.6209269  0.13871657 0.14774963]
 [1.73195199 1.46402199 1.60188207 ... 0.60815124 0.13871657 0.14774963]
 [1.73188611 1.46402199 1.60188207 ... 0.58259994 0.13871657 0.14774963]
 ...
 [1.73188611 1.4642893  1.58798488 ... 0.35263822 0.13871657 0.14774963]
 [1.73195199 1.4642893  1.58798488 ... 0.31431126 0.13871657 0.14774963]
 [1.73201787 1.4642893  1.58798488 ... 0.28875996 0.13871657 0.14774963]]
(49515, 13)


In [23]:
x2=shanghai2.iloc[:,6:11]
y2 = shanghai2.iloc[:,5]
model2 = stat.ols("y2 ~ x2" , data=shanghai2).fit()
print(model2.summary())

                            OLS Regression Results                            
Dep. Variable:                     y2   R-squared:                       0.047
Model:                            OLS   Adj. R-squared:                  0.047
Method:                 Least Squares   F-statistic:                     485.7
Date:                Sun, 10 Mar 2019   Prob (F-statistic):               0.00
Time:                        20:34:50   Log-Likelihood:            -2.2293e+05
No. Observations:               49515   AIC:                         4.459e+05
Df Residuals:                   49509   BIC:                         4.459e+05
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    487.8774     24.086     20.256      0.0

# 3. Missing Value, Transformasi

In [24]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(-10,10))
cut_shanghai= shanghai.iloc[:,5:11]
scaler.fit(cut_shanghai)
x_scaled = scaler.transform(cut_shanghai)
x_scaled= pd.DataFrame(x_scaled)
x_scaled.tail()

0         1         2    3         4         5
52579 -7.318612 -1.836735  2.135769  8.0 -5.652174 -9.729730
52580 -7.413249 -1.020408  3.294993  8.0 -5.217391 -9.657658
52581 -7.350158 -1.020408  3.294993  8.4 -5.217391 -9.603604
52582 -7.413249 -1.428571  3.247632  8.0 -5.652174 -9.549550
52583 -8.220947 -1.428571  3.247632  8.0 -5.652174 -9.513514

In [28]:
x3=cut_shanghai.iloc[:,1:6]
y3 = cut_shanghai.iloc[:,0]
model3 = stat.ols("y3 ~ x3" , data=cut_shanghai).fit()
print(model3.summary())

                            OLS Regression Results                            
Dep. Variable:                     y3   R-squared:                       0.040
Model:                            OLS   Adj. R-squared:                  0.040
Method:                 Least Squares   F-statistic:                     439.1
Date:                Sun, 10 Mar 2019   Prob (F-statistic):               0.00
Time:                        20:39:08   Log-Likelihood:            -2.5681e+05
No. Observations:               52584   AIC:                         5.136e+05
Df Residuals:                   52578   BIC:                         5.137e+05
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    464.0122     34.090     13.611      0.0

# 4. Missing Value, Outlier, Transformasi

In [29]:
from sklearn.preprocessing import normalize
xx = shanghai2.iloc[:,5:11]
xnorm = normalize(xx,norm='l2')
xnorm = pd.DataFrame(xnorm)
xnorm.tail()

0         1         2         3         4         5
49510  0.082634 -0.000961  0.062581  0.994497  0.004804  0.014413
49511  0.079740  0.000961  0.067510  0.994342  0.005764  0.018254
49512  0.081566  0.000960  0.067431  0.994143  0.005758  0.021111
49513  0.079731  0.000000  0.067301  0.994240  0.004803  0.024015
49514  0.055225  0.000000  0.067410  0.995845  0.004811  0.025979

In [30]:
x4=xnorm.iloc[:,1:6]
y4 = xnorm.iloc[:,0]
model4 = stat.ols("y4 ~ x4" , data=xnorm).fit()
print(model4.summary())

                            OLS Regression Results                            
Dep. Variable:                     y4   R-squared:                       0.391
Model:                            OLS   Adj. R-squared:                  0.391
Method:                 Least Squares   F-statistic:                     6363.
Date:                Sun, 10 Mar 2019   Prob (F-statistic):               0.00
Time:                        20:41:16   Log-Likelihood:             1.3160e+05
No. Observations:               49515   AIC:                        -2.632e+05
Df Residuals:                   49509   BIC:                        -2.631e+05
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      5.2726      0.031    170.559      0.0