# Praktikum 12 Maret 2019

In [1]:
import pandas as pd
import numpy as np

In [2]:
AUS=pd.read_csv("E:\weatherAUS.csv")
AUS.head()

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0  2008-12-01   Albury     13.4     22.9       0.6          NaN       NaN   
1  2008-12-02   Albury      7.4     25.1       0.0          NaN       NaN   
2  2008-12-03   Albury     12.9     25.7       0.0          NaN       NaN   
3  2008-12-04   Albury      9.2     28.0       0.0          NaN       NaN   
4  2008-12-05   Albury     17.5     32.3       1.0          NaN       NaN   

  WindGustDir  WindGustSpeed WindDir9am      ...      Humidity3pm  \
0           W           44.0          W      ...             22.0   
1         WNW           44.0        NNW      ...             25.0   
2         WSW           46.0          W      ...             30.0   
3          NE           24.0         SE      ...             16.0   
4           W           41.0        ENE      ...             33.0   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1007.7       1007.1       8.0       NaN     16.9     21.8         No   
1       1010.6       1007.8       NaN       NaN     17.2     24.3         No   
2       1007.6       1008.7       NaN       2.0     21.0     23.2         No   
3       1017.6       1012.8       NaN       NaN     18.1     26.5         No   
4       1010.8       1006.0       7.0       8.0     17.8     29.7         No   

   RISK_MM  RainTomorrow  
0      0.0            No  
1      0.0            No  
2      0.0            No  
3      1.0            No  
4      0.2            No  

[5 rows x 24 columns]

In [3]:
AUS.tail()

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  \
145455  2017-06-21    Uluru      2.8     23.4       0.0          NaN   
145456  2017-06-22    Uluru      3.6     25.3       0.0          NaN   
145457  2017-06-23    Uluru      5.4     26.9       0.0          NaN   
145458  2017-06-24    Uluru      7.8     27.0       0.0          NaN   
145459  2017-06-25    Uluru     14.9      NaN       0.0          NaN   

        Sunshine WindGustDir  WindGustSpeed WindDir9am      ...       \
145455       NaN           E           31.0         SE      ...        
145456       NaN         NNW           22.0         SE      ...        
145457       NaN           N           37.0         SE      ...        
145458       NaN          SE           28.0        SSE      ...        
145459       NaN         NaN            NaN        ESE      ...        

       Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  \
145455        24.0       1024.6       1020.3       NaN       NaN     10.1   
145456        21.0       1023.5       1019.1       NaN       NaN     10.9   
145457        24.0       1021.0       1016.8       NaN       NaN     12.5   
145458        24.0       1019.4       1016.5       3.0       2.0     15.1   
145459        36.0       1020.2       1017.9       8.0       8.0     15.0   

        Temp3pm  RainToday  RISK_MM  RainTomorrow  
145455     22.4         No      0.0            No  
145456     24.5         No      0.0            No  
145457     26.1         No      0.0            No  
145458     26.0         No      0.0            No  
145459     20.9         No      NaN           NaN  

[5 rows x 24 columns]

In [4]:
np.sum(AUS.isnull())

Date                 0
Location             0
MinTemp           1485
MaxTemp           1261
Rainfall          3261
Evaporation      62790
Sunshine         69835
WindGustDir      10326
WindGustSpeed    10263
WindDir9am       10566
WindDir3pm        4228
WindSpeed9am      1767
WindSpeed3pm      3062
Humidity9am       2654
Humidity3pm       4507
Pressure9am      15065
Pressure3pm      15028
Cloud9am         55888
Cloud3pm         59358
Temp9am           1767
Temp3pm           3609
RainToday         3261
RISK_MM           3267
RainTomorrow      3267
dtype: int64

In [5]:
AUS.describe()

MinTemp        MaxTemp       Rainfall   Evaporation  \
count  143975.000000  144199.000000  142199.000000  82670.000000   
mean       12.194034      23.221348       2.360918      5.468232   
std         6.398495       7.119049       8.478060      4.193704   
min        -8.500000      -4.800000       0.000000      0.000000   
25%         7.600000      17.900000       0.000000      2.600000   
50%        12.000000      22.600000       0.000000      4.800000   
75%        16.900000      28.200000       0.800000      7.400000   
max        33.900000      48.100000     371.000000    145.000000   

           Sunshine  WindGustSpeed   WindSpeed9am   WindSpeed3pm  \
count  75625.000000  135197.000000  143693.000000  142398.000000   
mean       7.611178      40.035230      14.043426      18.662657   
std        3.785483      13.607062       8.915375       8.809800   
min        0.000000       6.000000       0.000000       0.000000   
25%        4.800000      31.000000       7.000000      13.000000   
50%        8.400000      39.000000      13.000000      19.000000   
75%       10.600000      48.000000      19.000000      24.000000   
max       14.500000     135.000000     130.000000      87.000000   

         Humidity9am    Humidity3pm   Pressure9am    Pressure3pm  \
count  142806.000000  140953.000000  130395.00000  130432.000000   
mean       68.880831      51.539116    1017.64994    1015.255889   
std        19.029164      20.795902       7.10653       7.037414   
min         0.000000       0.000000     980.50000     977.100000   
25%        57.000000      37.000000    1012.90000    1010.400000   
50%        70.000000      52.000000    1017.60000    1015.200000   
75%        83.000000      66.000000    1022.40000    1020.000000   
max       100.000000     100.000000    1041.00000    1039.600000   

           Cloud9am      Cloud3pm        Temp9am       Temp3pm        RISK_MM  
count  89572.000000  86102.000000  143693.000000  141851.00000  142193.000000  
mean       4.447461      4.509930      16.990631      21.68339       2.360682  
std        2.887159      2.720357       6.488753       6.93665       8.477969  
min        0.000000      0.000000      -7.200000      -5.40000       0.000000  
25%        1.000000      2.000000      12.300000      16.60000       0.000000  
50%        5.000000      5.000000      16.700000      21.10000       0.000000  
75%        7.000000      7.000000      21.600000      26.40000       0.800000  
max        9.000000      9.000000      40.200000      46.70000     371.000000

In [7]:
AUS["MinTemp"]=AUS["MinTemp"].fillna((AUS["MinTemp"].mean()))
AUS["MaxTemp"]=AUS["MaxTemp"].fillna((AUS["MaxTemp"].mean()))
AUS["Rainfall"]=AUS["Rainfall"].fillna((AUS["Rainfall"].mean()))
AUS["Evaporation"]=AUS["Evaporation"].fillna((AUS["Evaporation"].mean()))
AUS["Sunshine"]=AUS["Sunshine"].fillna((AUS["Sunshine"].mean()))
AUS["WindGustSpeed"]=AUS["WindGustSpeed"].fillna((AUS["WindGustSpeed"].mean()))
AUS["WindSpeed9am"]=AUS["WindSpeed9am"].fillna((AUS["WindSpeed9am"].mean()))
AUS["WindSpeed3pm"]=AUS["WindSpeed3pm"].fillna((AUS["WindSpeed3pm"].mean()))
AUS["Humidity9am"]=AUS["Humidity9am"].fillna((AUS["Humidity9am"].mean()))
AUS["Humidity3pm"]=AUS["Humidity3pm"].fillna((AUS["Humidity3pm"].mean()))
AUS["Pressure9am"]=AUS["Pressure9am"].fillna((AUS["Pressure9am"].mean()))
AUS["Pressure3pm"]=AUS["Pressure3pm"].fillna((AUS["Pressure3pm"].mean()))
AUS["Cloud9am"]=AUS["Cloud9am"].fillna((AUS["Cloud9am"].mean()))
AUS["Cloud3pm"]=AUS["Cloud3pm"].fillna((AUS["Cloud3pm"].mean()))
AUS["Temp9am"]=AUS["Temp9am"].fillna((AUS["Temp9am"].mean()))
AUS["Temp3pm"]=AUS["Temp3pm"].fillna((AUS["Temp3pm"].mean()))
AUS["RISK_MM"]=AUS["RISK_MM"].fillna((AUS["RISK_MM"].mean()))

In [8]:
np.sum(AUS.isnull())

Date                 0
Location             0
MinTemp              0
MaxTemp              0
Rainfall             0
Evaporation          0
Sunshine             0
WindGustDir      10326
WindGustSpeed        0
WindDir9am       10566
WindDir3pm        4228
WindSpeed9am         0
WindSpeed3pm         0
Humidity9am          0
Humidity3pm          0
Pressure9am          0
Pressure3pm          0
Cloud9am             0
Cloud3pm             0
Temp9am              0
Temp3pm              0
RainToday         3261
RISK_MM              0
RainTomorrow      3267
dtype: int64

In [15]:
from scipy.stats import mode
AUS['WindGustDir']=AUS['WindGustDir'].fillna(AUS['WindGustDir']).dropna().mode()[0]
AUS['WindDir9am']=AUS['WindDir9am'].fillna(AUS['WindDir9am']).dropna().mode()[0]
AUS['WindDir3pm']=AUS['WindDir3pm'].fillna(AUS['WindDir3pm']).dropna().mode()[0]
AUS['RainToday']=AUS['RainToday'].fillna(AUS['RainToday']).dropna().mode()[0]
AUS['RainTomorrow']=AUS['RainTomorrow'].fillna(AUS['RainTomorrow']).dropna().mode()[0]

np.sum(AUS.isnull())

Date             0
Location         0
MinTemp          0
MaxTemp          0
Rainfall         0
Evaporation      0
Sunshine         0
WindGustDir      0
WindGustSpeed    0
WindDir9am       0
WindDir3pm       0
WindSpeed9am     0
WindSpeed3pm     0
Humidity9am      0
Humidity3pm      0
Pressure9am      0
Pressure3pm      0
Cloud9am         0
Cloud3pm         0
Temp9am          0
Temp3pm          0
RainToday        0
RISK_MM          0
RainTomorrow     0
dtype: int64

In [16]:
#Mengatasi Outlier

from scipy import stats
z = np.abs(stats.zscore(AUS._get_numeric_data()))
print(z)
AUS = AUS[(z<3).all(axis=1)]
print(AUS.shape)

[[0.22562535 0.03819883 0.22470698 ... 0.01024584 0.02234639 0.38331232]
 [0.73049893 0.28243552 0.3863391  ... 0.05775705 0.39939352 0.38331232]
 [0.14594832 0.36988125 0.3863391  ... 0.65956567 0.23349278 0.38331232]
 ...
 [1.04920703 0.54477272 0.3863391  ... 0.6865852  0.67086745 0.38331232]
 [0.66675732 0.55934701 0.3863391  ... 0.2748214  0.65578556 0.38331232]
 [0.46465642 0.00863539 0.3863391  ... 0.29065847 0.11339057 0.25560875]]
(123167, 24)


In [17]:
AUS

Date Location  MinTemp    MaxTemp   Rainfall  Evaporation  \
0       2008-12-01   Albury     13.4  22.900000   0.600000     5.468232   
1       2008-12-02   Albury      7.4  25.100000   0.000000     5.468232   
2       2008-12-03   Albury     12.9  25.700000   0.000000     5.468232   
3       2008-12-04   Albury      9.2  28.000000   0.000000     5.468232   
4       2008-12-05   Albury     17.5  32.300000   1.000000     5.468232   
5       2008-12-06   Albury     14.6  29.700000   0.200000     5.468232   
6       2008-12-07   Albury     14.3  25.000000   0.000000     5.468232   
7       2008-12-08   Albury      7.7  26.700000   0.000000     5.468232   
9       2008-12-10   Albury     13.1  30.100000   1.400000     5.468232   
10      2008-12-11   Albury     13.4  30.400000   0.000000     5.468232   
13      2008-12-14   Albury     12.6  21.000000   3.600000     5.468232   
14      2008-12-15   Albury      8.4  24.600000   0.000000     5.468232   
15      2008-12-16   Albury      9.8  27.700000   2.360918     5.468232   
18      2008-12-19   Albury     11.2  22.500000  10.600000     5.468232   
19      2008-12-20   Albury      9.8  25.600000   0.000000     5.468232   
20      2008-12-21   Albury     11.5  29.300000   0.000000     5.468232   
21      2008-12-22   Albury     17.1  33.000000   0.000000     5.468232   
22      2008-12-23   Albury     20.5  31.800000   0.000000     5.468232   
23      2008-12-24   Albury     15.3  30.900000   0.000000     5.468232   
24      2008-12-25   Albury     12.6  32.400000   0.000000     5.468232   
25      2008-12-26   Albury     16.2  33.900000   0.000000     5.468232   
26      2008-12-27   Albury     16.9  33.000000   0.000000     5.468232   
27      2008-12-28   Albury     20.1  32.700000   0.000000     5.468232   
28      2008-12-29   Albury     19.7  27.200000   0.000000     5.468232   
29      2008-12-30   Albury     12.5  24.200000   1.200000     5.468232   
30      2008-12-31   Albury     12.0  24.400000   0.800000     5.468232   
31      2009-01-01   Albury     11.3  26.500000   0.000000     5.468232   
32      2009-01-02   Albury      9.6  23.900000   0.000000     5.468232   
33      2009-01-03   Albury     10.5  28.800000   0.000000     5.468232   
34      2009-01-04   Albury     12.3  34.600000   0.000000     5.468232   
...            ...      ...      ...        ...        ...          ...   
145430  2017-05-27    Uluru      9.3  28.000000   0.000000     5.468232   
145431  2017-05-28    Uluru      8.0  24.600000   0.000000     5.468232   
145432  2017-05-29    Uluru     12.7  22.200000   0.000000     5.468232   
145433  2017-05-30    Uluru      9.4  22.700000   0.000000     5.468232   
145434  2017-05-31    Uluru      5.4  20.500000   0.000000     5.468232   
145435  2017-06-01    Uluru      5.6  19.400000   0.000000     5.468232   
145436  2017-06-02    Uluru      1.5  19.200000   0.000000     5.468232   
145437  2017-06-03    Uluru      3.8  19.800000   0.000000     5.468232   
145438  2017-06-04    Uluru      4.5  18.800000   0.000000     5.468232   
145439  2017-06-05    Uluru      4.9  20.700000   0.000000     5.468232   
145440  2017-06-06    Uluru      1.2  20.800000   0.000000     5.468232   
145441  2017-06-07    Uluru      0.5  21.700000   0.000000     5.468232   
145442  2017-06-08    Uluru      4.0  20.000000   0.000000     5.468232   
145443  2017-06-09    Uluru      3.4  19.800000   0.000000     5.468232   
145444  2017-06-10    Uluru      3.2  18.600000   0.000000     5.468232   
145445  2017-06-11    Uluru      2.4  19.100000   0.000000     5.468232   
145446  2017-06-12    Uluru      5.1  19.700000   0.000000     5.468232   
145447  2017-06-13    Uluru      2.5  21.200000   0.000000     5.468232   
145448  2017-06-14    Uluru      2.3  21.400000   0.000000     5.468232   
145449  2017-06-15    Uluru      2.6  22.500000   0.000000     5.468232   
145450  2017-06-16    Uluru      5.2  24.300000   0.000000     5.468232   
145451  2017-06-17    Uluru      6.4  2

In [18]:
AUS1=AUS.drop(columns=['Date','Location','WindGustDir','WindDir9am','WindDir3pm'])
AUS1['RainToday'].replace({'No':0,'Yes':1},inplace=True)
AUS1['RainTomorrow'].replace({'No':0,'Yes':1},inplace=True)
AUS1.tail()

MinTemp    MaxTemp  Rainfall  Evaporation  Sunshine  WindGustSpeed  \
145455      2.8  23.400000       0.0     5.468232  7.611178       31.00000   
145456      3.6  25.300000       0.0     5.468232  7.611178       22.00000   
145457      5.4  26.900000       0.0     5.468232  7.611178       37.00000   
145458      7.8  27.000000       0.0     5.468232  7.611178       28.00000   
145459     14.9  23.221348       0.0     5.468232  7.611178       40.03523   

        WindSpeed9am  WindSpeed3pm  Humidity9am  Humidity3pm  Pressure9am  \
145455          13.0          11.0         51.0         24.0       1024.6   
145456          13.0           9.0         56.0         21.0       1023.5   
145457           9.0           9.0         53.0         24.0       1021.0   
145458          13.0           7.0         51.0         24.0       1019.4   
145459          17.0          17.0         62.0         36.0       1020.2   

        Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
145455       1020.3  4.447461   4.50993     10.1     22.4          0   
145456       1019.1  4.447461   4.50993     10.9     24.5          0   
145457       1016.8  4.447461   4.50993     12.5     26.1          0   
145458       1016.5  3.000000   2.00000     15.1     26.0          0   
145459       1017.9  8.000000   8.00000     15.0     20.9          0   

         RISK_MM  RainTomorrow  
145455  0.000000             0  
145456  0.000000             0  
145457  0.000000             0  
145458  0.000000             0  
145459  2.360682             0

In [19]:
from sklearn.preprocessing import normalize
xnorm=normalize(AUS1,norm='l2') 
xnorm=pd.DataFrame(xnorm) 
xnorm.tail()

0         1    2         3         4         5         6   \
123162  0.001934  0.016161  0.0  0.003777  0.005257  0.021410  0.008978   
123163  0.002489  0.017492  0.0  0.003781  0.005262  0.015211  0.008988   
123164  0.003742  0.018639  0.0  0.003789  0.005274  0.025637  0.006236   
123165  0.005410  0.018728  0.0  0.003793  0.005279  0.019422  0.009017   
123166  0.010317  0.016078  0.0  0.003786  0.005270  0.027720  0.011771   

              7         8         9         10        11        12        13  \
123162  0.007597  0.035222  0.016575  0.707626  0.704656  0.003072  0.003115   
123163  0.006223  0.038718  0.014519  0.707643  0.704601  0.003075  0.003118   
123164  0.006236  0.036723  0.016629  0.707433  0.704523  0.003082  0.003125   
123165  0.004855  0.035376  0.016647  0.707095  0.705083  0.002081  0.001387   
123166  0.011771  0.042928  0.024926  0.706381  0.704789  0.005539  0.005539   

              14        15   16        17   18  
123162  0.006975  0.015470  0.0  0.000000  0.0  
123163  0.007536  0.016939  0.0  0.000000  0.0  
123164  0.008661  0.018084  0.0  0.000000  0.0  
123165  0.010474  0.018035  0.0  0.000000  0.0  
123166  0.010386  0.014471  0.0  0.001635  0.0

In [23]:
from sklearn.feature_selection import SelectKBest, chi2
x = AUS.drop(columns=['RainTomorrow'])
y = AUS.[['RainTomorrow']]
selector = SelectKBest(chi2, k='all').fit(x,y)
x_new=selector.transform(x)
scores=selector.scores_

SyntaxError: invalid syntax (<ipython-input-23-7e6765f31cbc>, line 3)